export const FETCH_USER_REQUEST ="FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS ="FETCH_USER_SUCCESS"
export const FETCH_USER_FAIL = "FETCH_USER_FAIL"

export const FETCH_PAYMENT_REQUEST ="FETCH_PAYMENT_REQUEST"
export const FETCH_PAYMENT_SUCCESS ="FETCH_PAYMENT_SUCCESS"
export const FETCH_PAYMENT_FAIL ="FETCH_PAYMENT_FAIL"

export const DELETE_PAYMENT_REQUEST ="DELETE_PAYMENT_REQUEST"
export const DELETE_PAYMENT_SUCCESS ="DELETE_PAYMENT_SUCCESS"
export const DELETE_PAYMENT_FAIL = "DELETE_PAYMENT_FAIL"

export const DELETE_USER_REQUEST ="DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS ="DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const FETCH_ALL_PAYMENT_REQUEST ="FETCH_ALL_PAYMENT_REQUEST"
export const FETCH_ALL_PAYMENT_SUCCESS ="FETCH_ALL_PAYMENT_SUCCESS"
export const FETCH_ALL_PAYMENT_FAIL ="FETCH_ALL_PAYMENT_FAIL"