export const LOGIN_REQUEST ='LOGIN_REQUEST'
export const LOGIN_SUCCESS ='LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'

export const INVESTOR_SIGNUP_REQUEST ='INVESTOR_SIGNUP_REQUEST'
export const INVESTOR_SIGNUP_SUCCESS ='INVESTOR_SIGNUP_SUCCESS'
export const INVESTOR_SIGNUP_FAILED = 'INVESTOR_SIGNUP_FAILED'


export const FETCH_PROFILE_REQUEST ='FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS ='FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED'

export const UPDATE_PROFILE_REQUEST ='UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS ='UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'
