export const PAYSTACK_REQUEST = "PAYSTACK_REQUEST"
export const PAYSTACK_SUCCESS = "PAYSTACK_SUCCESS"
export const PAYSTACK_FAIL = "PAYSTACK_FAIL"


export const COIN_UPDATE_REQUEST = " COIN_UPDATE_REQUEST"
export const COIN_UPDATE_SUCCESS = " COIN_UPDATE_SUCCESS"
export const COIN_UPDATE_FAIL = " COIN_UPDATE_FAIL"