export const FETCH_PRICE_REQUEST = "FETCH_PRICE_REQUEST"
export const FETCH_PRICE_SUCCESS = "FETCH_PRICE_SUCCESS"
export const FETCH_PRICE_FAIL = "FETCH_PRICE_FAIL"

export const UPDATE_PRICE_REQUEST = "UPDATE_PRICE_REQUEST"
export const UPDATE_PRICE_SUCCESS = "UPDATE_PRICE_SUCCESS"
export const UPDATE_PRICE_FAIL = "UPDATE_PRICE_FAIL"