export const STAKING_REQUEST = "STAKING_REQUEST"
export const STAKING_SUCCESS = "STAKING_SUCCESS"
export const STAKING_FAIL = "STAKING_FAIL"

export const FETCH_ALL_STAKE_REQUEST = "FETCH_ALL_STAKE_REQUEST"
export const FETCH_ALL_STAKE_SUCCESS = "FETCH_ALL_STAKE_SUCCESS"
export const FETCH_ALL_STAKE_FAIL = "FETCH_ALL_STAKE_FAIL"

export const FETCH_SINGLE_STAKE_REQUEST = "FETCH_SINGLE_STAKE_REQUEST"
export const FETCH_SINGLE_STAKE_SUCCESS = "FETCH_SINGLE_STAKE_SUCCESS"
export const FETCH_SINGLE_STAKE_FAIL = "FETCH_SINGLE_STAKE_FAIL"

